[build]
  base = "petex-app"
  command = "npm run build"

[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[[plugins]]
  package = "@netlify/plugin-nextjs"
